apiVersion: v1
kind: ConfigMap
metadata:
  name: sat-env-config
  namespace: sat-learning
data:
  RABBITMQ_URL: "amqp://rabbitmq.sat-learning.svc.cluster.local"
  PARTNER_URL: "http://sat-partner-mock-service.sat-learning.svc.cluster.local:3002"
  WEBHOOK_SECRET: "super-secret-key-123"
