apiVersion: apps/v1
kind: Deployment
metadata:
  name: sat-partner-mock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sat-partner-mock
  template:
    metadata:
      labels:
        app: sat-partner-mock
    spec:
      containers:
      - name: partner-mock
        image: sat-partner-mock-service:latest
        ports:
        - containerPort: 3002
